package com.example.ygd.lostandfound.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig studentsDaoConfig;
    private final DaoConfig newsDaoConfig;
    private final DaoConfig commentsDaoConfig;
    private final DaoConfig informationsDaoConfig;
    private final DaoConfig givesDaoConfig;
    private final DaoConfig messageDaoConfig;

    private final StudentsDao studentsDao;
    private final NewsDao newsDao;
    private final CommentsDao commentsDao;
    private final InformationsDao informationsDao;
    private final GivesDao givesDao;
    private final MessageDao messageDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        studentsDaoConfig = daoConfigMap.get(StudentsDao.class).clone();
        studentsDaoConfig.initIdentityScope(type);

        newsDaoConfig = daoConfigMap.get(NewsDao.class).clone();
        newsDaoConfig.initIdentityScope(type);

        commentsDaoConfig = daoConfigMap.get(CommentsDao.class).clone();
        commentsDaoConfig.initIdentityScope(type);

        informationsDaoConfig = daoConfigMap.get(InformationsDao.class).clone();
        informationsDaoConfig.initIdentityScope(type);

        givesDaoConfig = daoConfigMap.get(GivesDao.class).clone();
        givesDaoConfig.initIdentityScope(type);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        studentsDao = new StudentsDao(studentsDaoConfig, this);
        newsDao = new NewsDao(newsDaoConfig, this);
        commentsDao = new CommentsDao(commentsDaoConfig, this);
        informationsDao = new InformationsDao(informationsDaoConfig, this);
        givesDao = new GivesDao(givesDaoConfig, this);
        messageDao = new MessageDao(messageDaoConfig, this);

        registerDao(Students.class, studentsDao);
        registerDao(News.class, newsDao);
        registerDao(Comments.class, commentsDao);
        registerDao(Informations.class, informationsDao);
        registerDao(Gives.class, givesDao);
        registerDao(Message.class, messageDao);
    }
    
    public void clear() {
        studentsDaoConfig.getIdentityScope().clear();
        newsDaoConfig.getIdentityScope().clear();
        commentsDaoConfig.getIdentityScope().clear();
        informationsDaoConfig.getIdentityScope().clear();
        givesDaoConfig.getIdentityScope().clear();
        messageDaoConfig.getIdentityScope().clear();
    }

    public StudentsDao getStudentsDao() {
        return studentsDao;
    }

    public NewsDao getNewsDao() {
        return newsDao;
    }

    public CommentsDao getCommentsDao() {
        return commentsDao;
    }

    public InformationsDao getInformationsDao() {
        return informationsDao;
    }

    public GivesDao getGivesDao() {
        return givesDao;
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

}
