package com.example.ygd.lostandfound.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table "gives".
 */
public class Gives implements Parcelable {

    private Long id;
    private String s_id;
    private String gName;
    private String gLocation;
    private String gDate;
    private String gDescription;
    private String gImgUrl;
    private Double gLatitude;
    private Double gLongitude;

    public Gives() {
    }


    public Gives(Long id) {
        this.id = id;
    }

    public Gives(Long id, String s_id, String gName, String gLocation, String gDate, String gDescription, String gImgUrl, Double gLatitude, Double gLongitude) {
        this.id = id;
        this.s_id = s_id;
        this.gName = gName;
        this.gLocation = gLocation;
        this.gDate = gDate;
        this.gDescription = gDescription;
        this.gImgUrl = gImgUrl;
        this.gLatitude = gLatitude;
        this.gLongitude = gLongitude;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getS_id() {
        return s_id;
    }

    public void setS_id(String s_id) {
        this.s_id = s_id;
    }

    public String getGName() {
        return gName;
    }

    public void setGName(String gName) {
        this.gName = gName;
    }

    public String getGLocation() {
        return gLocation;
    }

    public void setGLocation(String gLocation) {
        this.gLocation = gLocation;
    }

    public String getGDate() {
        return gDate;
    }

    public void setGDate(String gDate) {
        this.gDate = gDate;
    }

    public String getGDescription() {
        return gDescription;
    }

    public void setGDescription(String gDescription) {
        this.gDescription = gDescription;
    }

    public String getGImgUrl() {
        return gImgUrl;
    }

    public void setGImgUrl(String gImgUrl) {
        this.gImgUrl = gImgUrl;
    }

    public Double getGLatitude() {
        return gLatitude;
    }

    public void setGLatitude(Double gLatitude) {
        this.gLatitude = gLatitude;
    }

    public Double getGLongitude() {
        return gLongitude;
    }

    public void setGLongitude(Double gLongitude) {
        this.gLongitude = gLongitude;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.s_id);
        dest.writeString(this.gName);
        dest.writeString(this.gLocation);
        dest.writeString(this.gDate);
        dest.writeString(this.gDescription);
        dest.writeString(this.gImgUrl);
        dest.writeValue(this.gLatitude);
        dest.writeValue(this.gLongitude);
    }

    protected Gives(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.s_id = in.readString();
        this.gName = in.readString();
        this.gLocation = in.readString();
        this.gDate = in.readString();
        this.gDescription = in.readString();
        this.gImgUrl = in.readString();
        this.gLatitude = (Double) in.readValue(Double.class.getClassLoader());
        this.gLongitude = (Double) in.readValue(Double.class.getClassLoader());
    }

    public static final Parcelable.Creator<Gives> CREATOR = new Parcelable.Creator<Gives>() {
        @Override
        public Gives createFromParcel(Parcel source) {
            return new Gives(source);
        }

        @Override
        public Gives[] newArray(int size) {
            return new Gives[size];
        }
    };
}
