package com.example.ygd.lostandfound.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "informations".
 */
public class Informations {

    private Long id;
    private Boolean iIsLost;
    private Integer type;
    private String s_id;
    private String iNum;

    public Informations() {
    }

    public Informations(Long id) {
        this.id = id;
    }

    public Informations(Long id, Boolean iIsLost, Integer type, String s_id, String iNum) {
        this.id = id;
        this.iIsLost = iIsLost;
        this.type = type;
        this.s_id = s_id;
        this.iNum = iNum;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getIIsLost() {
        return iIsLost;
    }

    public void setIIsLost(Boolean iIsLost) {
        this.iIsLost = iIsLost;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getS_id() {
        return s_id;
    }

    public void setS_id(String s_id) {
        this.s_id = s_id;
    }

    public String getINum() {
        return iNum;
    }

    public void setINum(String iNum) {
        this.iNum = iNum;
    }

}
