package com.example.ygd.lostandfound.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table "message".
 */
public class Message implements Parcelable {

    private Long id;
    private String p_id;
    private String l_id;

    public Message() {
    }

    public Message(Long id) {
        this.id = id;
    }

    public Message(Long id, String p_id, String l_id) {
        this.id = id;
        this.p_id = p_id;
        this.l_id = l_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getP_id() {
        return p_id;
    }

    public void setP_id(String p_id) {
        this.p_id = p_id;
    }

    public String getL_id() {
        return l_id;
    }

    public void setL_id(String l_id) {
        this.l_id = l_id;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.p_id);
        dest.writeString(this.l_id);
    }

    protected Message(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.p_id = in.readString();
        this.l_id = in.readString();
    }

    public static final Parcelable.Creator<Message> CREATOR = new Parcelable.Creator<Message>() {
        @Override
        public Message createFromParcel(Parcel source) {
            return new Message(source);
        }

        @Override
        public Message[] newArray(int size) {
            return new Message[size];
        }
    };
}
