package com.example.ygd.lostandfound.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table "news".
 */
public class News implements Parcelable {

    private Long id;
    private String nTitle;
    private String nDate;
    private String nImg;
    private String nContent;
    private Integer nAgree;
    private String nUrl;

    public News() {
    }



    public News(Long id) {
        this.id = id;
    }

    public News(Long id, String nTitle, String nDate, String nImg, String nContent, Integer nAgree, String nUrl) {
        this.id = id;
        this.nTitle = nTitle;
        this.nDate = nDate;
        this.nImg = nImg;
        this.nContent = nContent;
        this.nAgree = nAgree;
        this.nUrl = nUrl;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNTitle() {
        return nTitle;
    }

    public void setNTitle(String nTitle) {
        this.nTitle = nTitle;
    }

    public String getNDate() {
        return nDate;
    }

    public void setNDate(String nDate) {
        this.nDate = nDate;
    }

    public String getNImg() {
        return nImg;
    }

    public void setNImg(String nImg) {
        this.nImg = nImg;
    }

    public String getNContent() {
        return nContent;
    }

    public void setNContent(String nContent) {
        this.nContent = nContent;
    }

    public Integer getNAgree() {
        return nAgree;
    }

    public void setNAgree(Integer nAgree) {
        this.nAgree = nAgree;
    }

    public String getNUrl() {
        return nUrl;
    }

    public void setNUrl(String nUrl) {
        this.nUrl = nUrl;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.nTitle);
        dest.writeString(this.nDate);
        dest.writeString(this.nImg);
        dest.writeString(this.nContent);
        dest.writeValue(this.nAgree);
        dest.writeString(this.nUrl);
    }

    protected News(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.nTitle = in.readString();
        this.nDate = in.readString();
        this.nImg = in.readString();
        this.nContent = in.readString();
        this.nAgree = (Integer) in.readValue(Integer.class.getClassLoader());
        this.nUrl = in.readString();
    }

    public static final Parcelable.Creator<News> CREATOR = new Parcelable.Creator<News>() {
        @Override
        public News createFromParcel(Parcel source) {
            return new News(source);
        }

        @Override
        public News[] newArray(int size) {
            return new News[size];
        }
    };
}
