package com.example.ygd.lostandfound.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "students".
 */
public class Students {

    private String _id;
    private String sName;
    private String sPwd;
    private String sTel;
    private String sQQ;

    public Students() {
    }

    public Students(String _id) {
        this._id = _id;
    }

    public Students(String _id, String sName, String sPwd, String sTel, String sQQ) {
        this._id = _id;
        this.sName = sName;
        this.sPwd = sPwd;
        this.sTel = sTel;
        this.sQQ = sQQ;
    }

    public String get_id() {
        return _id;
    }

    public void set_id(String _id) {
        this._id = _id;
    }

    public String getSName() {
        return sName;
    }

    public void setSName(String sName) {
        this.sName = sName;
    }

    public String getSPwd() {
        return sPwd;
    }

    public void setSPwd(String sPwd) {
        this.sPwd = sPwd;
    }

    public String getSTel() {
        return sTel;
    }

    public void setSTel(String sTel) {
        this.sTel = sTel;
    }

    public String getSQQ() {
        return sQQ;
    }

    public void setSQQ(String sQQ) {
        this.sQQ = sQQ;
    }

}
